apiVersion: batch/v1
kind: Job
metadata:
  name: 'indexed-job'
spec:
  completions: 5
  parallelism: 5
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: app-job
        image: mochi256/performance_tester:latest
        command:
          - sh
          - -c
          - "performance_tester_client --host 192.168.0.250 -p 8000"
