apiVersion: v1
kind: Pod
metadata:
  name: app-server
  labels:
    app: app-server
spec:
  restartPolicy: Never
  containers:
  - name: app-server
    image: mochi256/performance_tester:latest
    tty: true
    command:
      - sh
      - -c
      - "performance_tester_server -c 1000000 -r 10000 -p 8000"
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-server
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.0.250
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8000
      targetPort: 8000
  selector:
    app: app-server
